[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/products"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
NPM_CONFIG_CI = "false"
CI = "false"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
NPM_CONFIG_CI = "false"
CI = "false" 